import { defineStore } from 'pinia';

export const useData = defineStore('data', {
    state: () => ({
        userData: {
            birthDate: '',
            gender: '',
            height: '',
            weight: '',
            heartRate: '',
            bloodPressure: '',
            sports: '',
            medications: '',
            chronicDiseases: '',
            allergies: '',
            diet: '',
            waterIntake: '',
            familyHistory: '',
            smoking: '',
            alcohol: '',
            sleep: '',
            physicalActivityLevel: '',
            workType: '',
            stressLevel: '',
            mentalHealth: '',
            cholesterolLevel: '',
            bloodSugarLevel: '',
            supplements: '',
            vaccinations: '',
            reproductiveHealth: '',
            visionAndHearing: '',
            sleepQuality: '',
            symptoms: '',
            medicalHistory: '',
            language: '',
            selectedModel: { id: 'deepseek/deepseek-r1:free', name: 'DeepSeek R1', type: 'advice2'}
        },
        messages: [] as { role: string, content: string }[],
        currentResponse: null as string | null,
        responseType: null as string | null,
        showOptionalFields: false,
        showPrivacyModal: false,
        showForm: true,
        showChat: true,
        acceptedPrivacyPolicy: false,
        controller: <AbortController | null>(null),
    })
});